inventarapp_xiv/urls.py
from django.urls import path
from . import views

app_name = 'inventar'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('material-handover/', views.material_handover_view, name='material-handover'),
    path('administration/<str:pk>', views.administration_view, name='administration'),
    path('administration/', views.administration_view, name='administration'),

    path('material-handover/<str:pk>/delete/', views.MaterialHandoverDelete.as_view(), name='material-handover-delete'),
    path('material-handover/<str:pk>/edit/', views.MaterialHandoverEdit.as_view(), name='material-handover-edit'),
    path('material-handover/create/', views.MaterialHandoverCreate.as_view(), name='material-handover-create'),

    path('employee/<str:pk>/delete/', views.EmployeeDelete.as_view(), name='employee-delete'),
    path('employee/<str:pk>/edit/', views.EmployeeEdit.as_view(), name='employee-edit'),
    path('employee/create/', views.EmployeeCreate.as_view(), name='employee-create'),

    path('credentials/<str:pk>/delete/', views.CredentialsDelete.as_view(), name='credentials-delete'),
    path('credentials/<str:pk>/edit/', views.CredentialsEdit.as_view(), name='credentials-edit'),
    path('credentials/create/', views.CredentialsCreate.as_view(), name='credentials-create'),

    path('hardware/<str:pk>/delete/', views.HardwareDelete.as_view(), name='hardware-delete'),
    path('hardware/<str:pk>/edit/', views.HardwareEdit.as_view(), name='hardware-edit'),
    path('hardware/create/', views.HardwareCreate.as_view(), name='hardware-create'),

    path('sim/<str:pk>/delete/', views.SimCardDelete.as_view(), name='sim-card-delete'),
    path('sim/<str:pk>/edit/', views.SimCardEdit.as_view(), name='sim-card-edit'),
    path('sim/create/', views.SimCardCreate.as_view(), name='sim-card-create'),

    path('key/<str:pk>/delete/', views.KeyDelete.as_view(), name='key-delete'),
    path('key/<str:pk>/edit/', views.KeyEdit.as_view(), name='key-edit'),
    path('key/create/', views.KeyCreate.as_view(), name='key-create'),

    path('others/<str:pk>/delete/', views.OthersDelete.as_view(), name='others-delete'),
    path('others/<str:pk>/edit/', views.OthersEdit.as_view(), name='others-edit'),
    path('others/create/', views.OthersCreate.as_view(), name='others-create'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventarapp_xiv.urls')),
]

inventarapp_xiv/models.py
from django.utils import timezone
from django.db import models

CHOICES_CONTRACT_TYPE = [
    ('Werkstudent', 'Werkstudent'),
    ('Angestellter', 'Angestellter'),
]

CHOICES_EMPLOYEE_STATUS = [
    ('Aktiv', 'Aktiv'),
    ('Inaktiv', 'Inaktiv'),
]

CHOICES_ACCOUNT_TYPE = [
    ('MacBook', 'MacBook'),
    ('Apple_ID', 'Apple ID'),
    ('Office_365', 'Office 365'),
    ('Egencia', 'Egencia'),
    ('BCS', 'BCS'),
]

CHOICES_HARDWARE_TYPE = [
    ('Handy', 'Handy'),
    ('Notebook', 'Notebook'),
    ('Festplatte', 'Festplatte'),
    ('Zubehör', 'Zubehör'),
]


class Employee(models.Model):
    personnel_number = models.CharField(max_length=20, primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=50)
    abbreviation = models.CharField(max_length=20)
    contract_type = models.CharField(max_length=50, choices=CHOICES_CONTRACT_TYPE)
    status = models.CharField(max_length=20, choices=CHOICES_EMPLOYEE_STATUS)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class InitialCredentials(models.Model):
    account_type = models.CharField(max_length=30, choices=CHOICES_ACCOUNT_TYPE)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.account_type + '/' + self.username


class Hardware(models.Model):
    hardware_type = models.CharField(max_length=15, choices=CHOICES_HARDWARE_TYPE)
    description = models.TextField()
    serial_nummer = models.CharField(max_length=20)
    hint = models.CharField(max_length=100)

    def __str__(self):
        return self.hardware_type + '/' + self.serial_nummer


class SimCard(models.Model):
    phone_number = models.CharField(max_length=50)
    card_number = models.CharField(max_length=20)
    PIN = models.CharField(max_length=10)
    PUK = models.CharField(max_length=10)

    def __str__(self):
        return self.phone_number


class Key(models.Model):
    key_number = models.CharField(max_length=50)
    hint = models.CharField(max_length=100)

    def __str__(self):
        return self.key_number


class Others(models.Model):
    description = models.TextField()
    hint = models.CharField(max_length=100)

    def __str__(self):
        return self.description


class MaterialHandover(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT)
    initial_credentials = models.ManyToManyField(InitialCredentials, blank=True, null=True)
    hardware = models.ManyToManyField(Hardware, blank=True, null=True)
    sim_card = models.ManyToManyField(SimCard, blank=True, null=True)
    key = models.ManyToManyField(Key, blank=True, null=True)
    others = models.ManyToManyField(Others, blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    returning_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.employee.personnel_number

inventarapp_xiv/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=35, label='Username')
    password = forms.CharField(min_length=6, max_length=50, label='Passwort', widget=forms.PasswordInput)
    password2 = forms.CharField(min_length=6, max_length=50, label='Passwort Wiederholung', widget=forms.PasswordInput)
    email = forms.EmailField(label='Email')

    def clean_password2(self):
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password and password2 and password != password2:
            raise forms.ValidationError('Passwörter stimmen nicht überein')
        return password

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError('Diesen Username gibt es schon')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError('Diese Email gibt es schon')
        return email


class LoginForm(forms.Form):
    username = forms.CharField(max_length=35, label='Username eintragen')
    password = forms.CharField(min_length=6, max_length=50, label='Password eintragen', widget=forms.PasswordInput)

inventarapp_xiv/views.py
from django.db.models import Q

from .forms import LoginForm, RegisterForm
from .models import Employee, InitialCredentials, Hardware, SimCard, Key, Others, MaterialHandover
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView, CreateView


def index(request):
    return render(request, 'inventar/base.html')


def register_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('inventar:index'))
    register_form = RegisterForm()
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data["username"]
            password = register_form.cleaned_data["password"]
            email = register_form.cleaned_data["email"]
            User.objects.create_user(username=username, password=password, email=email)
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                if request.user.is_superuser:
                    return redirect(reverse('inventar:admin'))
                else:
                    return redirect(reverse('inventar:index'))
    return render(request, 'inventar/register.html', {'register_form': register_form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('inventar:index'))
    login_form = LoginForm()
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data["username"]
            password = login_form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                if request.user.is_superuser:
                    return redirect(reverse('inventar:admin'))
                else:
                    return redirect(reverse('inventar:index'))

    return render(request, 'inventar/login.html', {'login_form': login_form})


@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse('inventar:index'))


@login_required
def administration_view(request, pk='employee'):
    if request.GET.get('q') == None:
        query = ''
    else:
        query = request.GET.get('q')

    if pk == 'employee':
        employees = filter_employee(request)
    else:
        employees = Employee.objects.all()

    if pk == 'credentials':
        credential_list = filter_credentials(request)
        credential_list = filter_credentials_exists(credential_list)

    else:
        credential_list = InitialCredentials.objects.all()
        credential_list = filter_credentials_exists(credential_list)

    if pk == 'hardware':
        hardware_list = filter_hardware(request)
        hardware_list = filter_hardware_exists(hardware_list)
    else:
        hardware_list = Hardware.objects.all()
        hardware_list = filter_hardware_exists(hardware_list)

    if pk == 'sim':
        sim_card_list = filter_sim_cards(request)
        sim_card_list = filter_sim_exists(sim_card_list)
    else:
        sim_card_list = SimCard.objects.all()
        sim_card_list = filter_sim_exists(sim_card_list)

    if pk == 'key':
        key_list = filter_key(request)
        key_list = filter_key_exists(key_list)
    else:
        key_list = Key.objects.all()
        key_list = filter_key_exists(key_list)

    if pk == 'others':
        other_list = filter_others(request)
        other_list = filter_others_exists(other_list)
    else:
        other_list = Others.objects.all()
        other_list = filter_others_exists(other_list)

    context = {
        'query': query,
        'active_tab': pk,
        'employees': employees,
        'credential_list': credential_list,
        'hardware_list': hardware_list,
        'sim_card_list': sim_card_list,
        'key_list': key_list,
        'other_list': other_list,
    }

    return render(request, 'inventar/administration.html', context)


def is_valid_queryparam(param):
    return param != '' and param is not None


def filter_employee(request):
    employees = Employee.objects.all()

    _query = request.GET.get('q')

    if is_valid_queryparam(_query):
        employees = employees.filter(
            Q(personnel_number__contains=_query) | Q(first_name__contains=_query) | Q(last_name__contains=_query) | Q(
                email__contains=_query) | Q(phone__contains=_query) | Q(abbreviation__contains=_query) | Q(
                contract_type__contains=_query) | Q(status__contains=_query))
    return employees


def filter_credentials(request):
    credential_list = InitialCredentials.objects.all()

    _query = request.GET.get('q')

    if is_valid_queryparam(_query):
        credential_list = credential_list.filter(
            Q(account_type__contains=_query) | Q(username__contains=_query))
    return credential_list


def filter_hardware(request):
    hardware_list = Hardware.objects.all()

    _query = request.GET.get('q')

    if is_valid_queryparam(_query):
        hardware_list = hardware_list.filter(
            Q(hardware_type__contains=_query) | Q(description__contains=_query) | Q(serial_nummer__contains=_query) | Q(
                hint__contains=_query))

    return hardware_list


def filter_sim_cards(request):
    sim_card_list = SimCard.objects.all()

    _query = request.GET.get('q')

    if is_valid_queryparam(_query):
        sim_card_list = sim_card_list.filter(
            Q(phone_number__contains=_query) | Q(card_number__contains=_query))

    return sim_card_list


def filter_key(request):
    key_list = Key.objects.all()

    _query = request.GET.get('q')

    if is_valid_queryparam(_query):
        key_list = key_list.filter(
            Q(key_number__contains=_query) | Q(hint__contains=_query))

    return key_list


def filter_others(request):
    other_list = Others.objects.all()

    _query = request.GET.get('q')

    if is_valid_queryparam(_query):
        other_list = other_list.filter(
            Q(description__contains=_query) | Q(hint__contains=_query))

    return other_list


def filter_credentials_exists(list):
    filtered_list = []

    for credentials in list:
        credentials.borrowed = MaterialHandover.objects.filter(initial_credentials__pk=credentials.pk).exists()
        filtered_list.append(credentials)

    return filtered_list


def filter_hardware_exists(list):
    filtered_list = []

    for hardware in list:
        hardware.borrowed = MaterialHandover.objects.filter(hardware__pk=hardware.pk).exists()
        filtered_list.append(hardware)

    return filtered_list


def filter_sim_exists(list):
    filtered_list = []

    for sim in list:
        sim.borrowed = MaterialHandover.objects.filter(sim_card__pk=sim.pk).exists()
        filtered_list.append(sim)

    return filtered_list


def filter_key_exists(list):
    filtered_list = []

    for key in list:
        key.borrowed = MaterialHandover.objects.filter(key__pk=key.pk).exists()
        filtered_list.append(key)

    return filtered_list


def filter_others_exists(list):
    filtered_list = []

    for other in list:
        other.borrowed = MaterialHandover.objects.filter(others__pk=other.pk).exists()
        filtered_list.append(other)

    return filtered_list


class EmployeeCreate(CreateView):
    model = Employee
    fields = [
        'personnel_number',
        'first_name',
        'last_name',
        'email',
        'phone',
        'abbreviation',
        'contract_type',
        'status']
    template_name = 'inventar/create.html'
    success_url = reverse_lazy('inventar:administration')


class EmployeeEdit(UpdateView):
    model = Employee
    fields = [
        'personnel_number',
        'first_name',
        'last_name',
        'email',
        'phone',
        'abbreviation',
        'contract_type',
        'status']
    template_name = 'inventar/edit.html'
    success_url = reverse_lazy('inventar:administration')


class EmployeeDelete(DeleteView):
    model = Employee
    template_name = 'inventar/delete.html'
    success_url = reverse_lazy('inventar:administration')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(EmployeeDelete, self).post(request, *args, **kwargs)


class CredentialsCreate(CreateView):
    model = InitialCredentials
    fields = [
        'account_type',
        'username',
        'password',
    ]
    template_name = 'inventar/create.html'
    success_url = reverse_lazy('inventar:administration')


class CredentialsEdit(UpdateView):
    model = InitialCredentials
    fields = [
        'account_type',
        'username',
        'password',
    ]
    template_name = 'inventar/edit.html'
    success_url = reverse_lazy('inventar:administration')


class CredentialsDelete(DeleteView):
    model = InitialCredentials
    template_name = 'inventar/delete.html'
    success_url = reverse_lazy('inventar:administration')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(CredentialsDelete, self).post(request, *args, **kwargs)


class HardwareCreate(CreateView):
    model = Hardware
    fields = [
        'hardware_type',
        'description',
        'serial_nummer',
        'hint',
    ]
    template_name = 'inventar/create.html'

inventarapp_xiv/templates/inventar/administration.html
{% extends 'inventar/base.html' %}
{% load bootstrap4 %}
{% load bootstrap_icons %}

{% block title %} Verwaltung {% endblock %}

{% block authForm %}
<ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link {% if active_tab == 'employee' %} active {% endif %}" id="employee-tab" data-toggle="tab"
           href="#employee" role="tab"
           aria-controls="employee"
           aria-selected="true" style="color: #305695"> {% bs_icon 'people' %} Mitarbeiter</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if active_tab == 'credentials' %} active {% endif %}" id="credentials-tab"
           data-toggle="tab" href="#credentials" role="tab"
           aria-controls="credentials"
           aria-selected="false"
           style="color: #305695">{% bs_icon 'eye-slash' %} Initiale Kennwörter</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if active_tab == 'hardware' %} active {% endif %}" id="hardware-tab" data-toggle="tab"
           href="#hardware" role="tab"
           aria-controls="hardware"
           aria-selected="false"
           style="color: #305695">{% bs_icon 'laptop' %}Hardware</a>
    </li>
    <li class="nav-item {% if active_tab == 'sim' %} active {% endif %}">
        <a class="nav-link" id="sim-card-tab" data-toggle="tab" href="#sim-card" role="tab"
           aria-controls="sim-card"
           aria-selected="false"
           style="color: #305695">{% bs_icon 'sim' %}Sim Karten</a>
    </li>
    <li class="nav-item {% if active_tab == 'key' %} active {% endif %}">
        <a class="nav-link" id="key-tab" data-toggle="tab" href="#key" role="tab"
           aria-controls="key"
           aria-selected="false"
           style="color: #305695">{% bs_icon 'key' %}Schlüssel</a>
    </li>
    <li class="nav-item {% if active_tab == 'others' %} active {% endif %}">
        <a class="nav-link" id="others-tab" data-toggle="tab" href="#others" role="tab"
           aria-controls="others"
           aria-selected="false"
           style="color: #305695">{% bs_icon 'box' %}Sonstiges</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade {% if active_tab == 'employee' %} show active {% endif %}"
         id="employee"
         role="tabpanel" aria-labelledby="employee-tab"
         style="width:90vw;height: 95vh;">
        {% block employee %}{% include 'inventar/tabs/employee.html' %}{% endblock %}
    </div>

    <div class="tab-pane fade {% if active_tab == 'credentials' %} show active {% endif %}" id="credentials"
         role="tabpanel" aria-labelledby="credentials-tab">
        {% block credentials %}{% include 'inventar/tabs/credentials.html' %}{% endblock %}
    </div>
    <div class="tab-pane fade {% if active_tab == 'hardware' %} show active {% endif %}" id="hardware" role="tabpanel"
         aria-labelledby="hardware-tab">
        {% block hardware %}{% include 'inventar/tabs/hardware.html' %}{% endblock %}
    </div>
    <div class="tab-pane fade {% if active_tab == 'sim' %} show active {% endif %}" id="sim-card" role="tabpanel"
         aria-labelledby="sim-card-tab">
        {% block sim-card %}{% include 'inventar/tabs/sim-card.html' %}{% endblock %}
    </div>
    <div class="tab-pane fade {% if active_tab == 'key' %} show active {% endif %}" id="key" role="tabpanel"
         aria-labelledby="key-tab">
        {% block key %}{% include 'inventar/tabs/key.html' %}{% endblock %}
    </div>
    <div class="tab-pane fade {% if active_tab == 'others' %} show active {% endif %}" id="others" role="tabpanel"
         aria-labelledby="others-tab">
        {% block others %}{% include 'inventar/tabs/others.html' %}{% endblock %}
    </div>
</div>
{% endblock %}

inventarapp_xiv/templates/inventar/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'inventarapp_xiv/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar navbar-dark bg-dark">

    <a class="navbar-brand" href="/">Inventar-App</a>
    <span class="navbar-text">


      {% if request.user.is_authenticated %}
        <a href="/administration" class="btn btn-dark">Verwaltung</a>
        <a href="/material-handover" class="btn btn-dark">Materialübergabe</a>
        <a href="{% url 'inventar:logout' %}" class="btn btn-danger">logout</a>

      {% else %}
      <a href="{% url 'inventar:login' %}" class="btn btn-success">login</a>
      <a href="{% url 'inventar:register' %}" class="btn btn-secondary">Account Anlegen</a>
      {% endif %}
    </span>

</nav>

<div class="container-fluid">
    <div class="col" >
        <div>
            {% block authForm %}
            <div>
                <h2> Willkommen in den Inventarlisten </h2>
            </div>
            {% endblock %}
        </div>
    </div>
</div>

</body>

</html>

inventarapp_xiv/templates/inventar/create.html
{% extends "inventar/base.html" %}
{% load bootstrap4 %}

{% block title %} login{% endblock %}

{% block authForm %}

<div class="d-flex justify-content-center p-4">
    <form method="post" class="m-1" style="width: 350px">{% csrf_token %}
        {% for field in form %}
        <div class="form-group{% if field.errors %} invalid{% endif %} d-flex flex-row align-items-center align-content-center justify-content-between">
            <label><strong>{{ field.label }}</strong></label>
            {{ field }}
            {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="d-flex flex-row align-items-center justify-content-end mt-5">
            <a class="p-3" href="{% url 'inventar:administration' %}">
                <button type="button" class="btn btn-light"><strong>Zurück</strong></button>
            </a>
            <button class="btn btn-primary" type="submit">Speichern</button>
        </div>
    </form>
</div>
{% endblock %}

inventarapp_xiv/templates/inventar/delete.html
{% extends "inventar/base.html" %}
{% load bootstrap4 %}

{% block title %} login{% endblock %}

{% block authForm %}

<div class="d-flex justify-content-center p-4">
    <form action="" method="post">{% csrf_token %}
        <p>Möchten Sie wirklich "{{ object }}" löschen?</p>
        <input type="submit" value="Bestätigen" />
        <input type="submit" name="cancel" value="Abbrechen" />
    </form>
</div>
{% endblock %}

inventarapp_xiv/templates/inventar/edit.html
{% extends "inventar/base.html" %}
{% load bootstrap4 %}

{% block title %} login{% endblock %}

{% block authForm %}

<div class="d-flex justify-content-center p-4">
    <form method="post" class="m-1">{% csrf_token %}
        {% for field in form %}
        <div class="form-group{% if field.errors %} invalid{% endif %} d-flex flex-row align-items-center align-content-center justify-content-between">
            <label><strong>{{ field.label }}</strong></label>
            {{ field }}
            {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="d-flex flex-row align-items-center justify-content-end mt-5">
            <a class="p-3" href="{% url 'inventar:administration' %}">
                <button type="button" class="btn btn-light"><strong>Zurück</strong></button>
            </a>
            <button class="btn btn-primary" type="submit">Bearbeiten</button>
        </div>
    </form>
</div>
{% endblock %}

inventarapp_xiv/templates/inventar/login.html
{% extends "inventar/base.html" %}
{% load bootstrap4 %}

{% block title %} login{% endblock %}

{% block authForm %}


<form method="POST" action="">
    {% csrf_token %}
    {% bootstrap_form login_form %}
    <button type="submit" class="btn btn-dark">login</button>
</form>


{% endblock %}

inventarapp_xiv/templates/inventar/material-handover.html
{% extends 'inventar/base.html' %}
{% load bootstrap_icons %}
{% load bootstrap4 %}

{% block title %} Materialübergabe {% endblock %}

{% block authForm %}
<a class="col-3 d-flex justify-content-start" style="margin: 3rem 0 16px 0;" href="{% url 'inventar:material-handover-create' %}"
   style="color: #ffffff; text-decoration: none">
    <button type="button" class="btn btn-secondary">
        {% bs_icon 'plus' size='1.5em' %} Materialübergabe
    </button>
</a>

<table class="table table-sm table-striped">
    <thead style="color: #305695">
    <tr>
        <th scope="col"></th>
        <th scope="col">employee</th>
        <th scope="col">created_date</th>
        <th scope="col">returning_date</th>
        <th scope="col">actions</th>
    </tr>
    </thead>
    <tbody>
    {% for mh in material_handovers %}
    <tr>
        <th scope="row">
            {% bs_icon 'clipboard' size='1.5em' %}
        </th>
        <th scope="row">{{ mh.employee}}</th>
        <td>{{ mh.created_date }}</td>
        <td>{{ mh.returning_date }}</td>
        <td>
            <a href="{% url 'inventar:material-handover-edit' mh.id %}" style="color: #305695">
                {% bs_icon 'pen' size='1.5em' %}
            </a>
            <a href="{% url 'inventar:material-handover-delete' mh.id%}" style="color: #c71b1b">
                {% bs_icon 'trash' size='1.5em' %}
            </a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

inventarapp_xiv/templates/inventar/register.html
{% extends "inventar/base.html" %}
{% load bootstrap4 %}

{% block title %} Konto anlegen{% endblock %}

{% block authForm %}

<form method="POST" action="">
    {% csrf_token %}
    {% bootstrap_form register_form %}

    <button type="submit" class="btn btn-dark">Konto anlegen</button>
</form>


{% endblock %}